# Generated by Django 2.1.4 on 2018-12-26 11:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Lehrstuhl-name')),
            ],
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel der Arbeit')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Erstellungsdatum')),
                ('additional', models.TextField(blank=True, max_length=1000, verbose_name='weitere Beschreibung')),
                ('contact', models.EmailField(max_length=254, verbose_name='E-Mail der Kontaktperson:')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='frühester Beginn')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('pdf', models.FileField(blank=True, upload_to='uploads/', verbose_name='PDF mit Ausschreibung')),
                ('type', models.CharField(choices=[('B.Sc.', 'Bachelor of Science'), ('M.Sc.', 'Master of Science'), ('B.Ed.', 'Bachelor of Education'), ('M.Ed.', 'Master of Education'), ('Project', 'Forschungsprojekt')], max_length=3)),
                ('chair', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='provided_by', to='abschlussarbeiten.Chair', verbose_name='angeboten durch Lehrstuhl')),
            ],
        ),
    ]
