# Generated by Django 2.1.4 on 2018-12-26 17:35

from django.db import migrations, models
import django.utils.timezone
import tagulous.models.fields
import tagulous.models.models


class Migration(migrations.Migration):

    dependencies = [
        ('abschlussarbeiten', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tagulous_Thesis_tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.AlterModelOptions(
            name='chair',
            options={'verbose_name': 'Lehrstuhl', 'verbose_name_plural': 'Lehrstühle'},
        ),
        migrations.AlterModelOptions(
            name='thesis',
            options={'verbose_name': 'Abschlussarbeit', 'verbose_name_plural': 'Abschlussarbeiten'},
        ),
        migrations.AlterField(
            model_name='thesis',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='frühester Beginn'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='type',
            field=models.CharField(choices=[('BSC', 'Bachelor of Science'), ('MSC', 'Master of Science'), ('BED', 'Bachelor of Education'), ('MED', 'Master of Education'), ('PRO', 'Forschungsprojekt')], max_length=3, verbose_name='Art der Arbeit'),
        ),
        migrations.AlterUniqueTogether(
            name='tagulous_thesis_tags',
            unique_together={('slug',)},
        ),
        migrations.AddField(
            model_name='thesis',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, help_text='Enter a comma-separated tag string', to='abschlussarbeiten.Tagulous_Thesis_tags'),
        ),
    ]
