# Generated by Django 2.1.4 on 2018-12-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abschlussarbeiten', '0002_auto_20181226_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='chair',
            name='head',
            field=models.CharField(default='', max_length=50, verbose_name='Leitung'),
        ),
        migrations.AlterField(
            model_name='chair',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Lehrstuhl-Name'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='pdf',
            field=models.FileField(blank=True, upload_to='', verbose_name='PDF mit Ausschreibung'),
        ),
    ]
