# Generated by Django 2.1.4 on 2018-12-27 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abschlussarbeiten', '0003_auto_20181227_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='chair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provided_by', to='abschlussarbeiten.Chair', verbose_name='angeboten durch Lehrstuhl'),
        ),
    ]
